USE [Cerner_CDS_Extract]
GO

/****** Object:  StoredProcedure [dbo].[usp_NON_CDE_EDW_F_Session_WITH_SEQUENCE_FOR_SURGINET]    Script Date: 06/01/2019 23:23:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[usp_NON_CDE_EDW_F_Session_WITH_SEQUENCE_FOR_SURGINET] 
	-- Add the parameters for the stored procedure here
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NON_CDE_EDW_F_Session_WITH_SEQUENCE]') AND type in (N'U'))
	DROP TABLE NON_CDE_EDW_F_Session_WITH_SEQUENCE

CREATE TABLE [dbo].[NON_CDE_EDW_F_Session_WITH_SEQUENCE](
	[Session_Sequence_NBR] [bigint] NULL,
	[EDW_F_SESSION_ID] [varchar](50) NOT NULL,
	[HEALTH_SYSTEM_SOURCE_ID] [varchar](50) NULL,
	[SESSION_SK] [varchar](50) NULL,
	[SESSION_BEG_DT_TM] [varchar](50) NULL,
	[LOC_SESSION_BEG_DT_TM] [varchar](50) NULL,
	[SESSION_END_DT_TM] [varchar](50) NULL,
	[LOC_SESSION_END_DT_TM] [varchar](50) NULL,
	[SESSION_DURATION] [varchar](50) NULL,
	[THEATRE_REF] [varchar](50) NULL,
	[NUMBER_OF_PLANNED_CASES] [varchar](50) NULL,
	[TOT_SCHED_CASE_TIME_MINS] [varchar](50) NULL,
	[NUMBER_OF_ACTUAL_CASES_HELD] [varchar](50) NULL,
	[OBSERVED_CASE_TIME_MINS] [varchar](50) NULL,
	[OBSERVED_ANESTHESIA_TIME_MINS] [varchar](50) NULL,
	[OBSERVED_SURGERY_TIME_MINS] [varchar](50) NULL,
	[TOTAL_COLLECTION_TIME_MINS] [varchar](50) NULL,
	[ACTUAL_FIRST_CASE_START_DT_TM] [varchar](50) NULL,
	[LOC_ACTUAL_FRST_CASE_STR_DT_TM] [varchar](50) NULL,
	[SCHED_FIRST_CASE_START_DT_TM] [varchar](50) NULL,
	[LOC_SCHED_FRST_CASE_STRT_DT_TM] [varchar](50) NULL,
	[NUMBER_OF_DELAYS] [varchar](50) NULL,
	[TOTAL_DELAY_DURATION_MINS] [varchar](50) NULL,
	[TOTAL_TURNAROUND_TIME_MINS] [varchar](50) NULL,
	[ACTUAL_LAST_CASE_STOP_DT_TM] [varchar](50) NULL,
	[LOC_ACTUAL_LAST_CASE_STP_DT_TM] [varchar](50) NULL,
	[NUMBER_OF_CANCELLATIONS] [varchar](50) NULL,
	[NUMBER_SAME_DAY_CANCELLATIONS] [varchar](50) NULL,
	[UNDER_UTILISATION_MINS] [varchar](50) NULL,
	[SCHED_LAST_CASE_STOP_DT_TM] [varchar](50) NULL,
	[LOC_SCHED_LAST_CASE_STOP_DT_TM] [varchar](50) NULL,
	[TOT_TIME_PAT_IN_THEATRE_MINS] [varchar](50) NULL,
	[EXTRACT_DT_TM] [varchar](50) NULL,
	[FIRST_PROCESS_DT_TM] [varchar](50) NULL,
	[LAST_PROCESS_DT_TM] [varchar](50) NULL,
	[UPDT_DT_TM] [varchar](50) NULL,
	[UPDT_TASK] [varchar](50) NULL,
	[UPDT_USER] [varchar](50) NULL,
	[CDE_FILENAME] [nvarchar](100) NULL,
	[ROW_ID] [int] NULL,
	[TIMESTAMP_RECORD_ADDED] [datetime] NULL,
	[TIMESTAMP_RECORD_UPDATED] [datetime] NULL,
 CONSTRAINT [PK_NON_CDE_EDW_F_Session_WITH_SEQUENCE] PRIMARY KEY CLUSTERED 
(
	[EDW_F_SESSION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

	INSERT INTO [dbo].[NON_CDE_EDW_F_Session_WITH_SEQUENCE]
			   ([Session_Sequence_NBR]
			   ,[EDW_F_SESSION_ID]
			   ,[HEALTH_SYSTEM_SOURCE_ID]
			   ,[SESSION_SK]
			   ,[SESSION_BEG_DT_TM]
			   ,[LOC_SESSION_BEG_DT_TM]
			   ,[SESSION_END_DT_TM]
			   ,[LOC_SESSION_END_DT_TM]
			   ,[SESSION_DURATION]
			   ,[THEATRE_REF]
			   ,[NUMBER_OF_PLANNED_CASES]
			   ,[TOT_SCHED_CASE_TIME_MINS]
			   ,[NUMBER_OF_ACTUAL_CASES_HELD]
			   ,[OBSERVED_CASE_TIME_MINS]
			   ,[OBSERVED_ANESTHESIA_TIME_MINS]
			   ,[OBSERVED_SURGERY_TIME_MINS]
			   ,[TOTAL_COLLECTION_TIME_MINS]
			   ,[ACTUAL_FIRST_CASE_START_DT_TM]
			   ,[LOC_ACTUAL_FRST_CASE_STR_DT_TM]
			   ,[SCHED_FIRST_CASE_START_DT_TM]
			   ,[LOC_SCHED_FRST_CASE_STRT_DT_TM]
			   ,[NUMBER_OF_DELAYS]
			   ,[TOTAL_DELAY_DURATION_MINS]
			   ,[TOTAL_TURNAROUND_TIME_MINS]
			   ,[ACTUAL_LAST_CASE_STOP_DT_TM]
			   ,[LOC_ACTUAL_LAST_CASE_STP_DT_TM]
			   ,[NUMBER_OF_CANCELLATIONS]
			   ,[NUMBER_SAME_DAY_CANCELLATIONS]
			   ,[UNDER_UTILISATION_MINS]
			   ,[SCHED_LAST_CASE_STOP_DT_TM]
			   ,[LOC_SCHED_LAST_CASE_STOP_DT_TM]
			   ,[TOT_TIME_PAT_IN_THEATRE_MINS]
			   ,[EXTRACT_DT_TM]
			   ,[FIRST_PROCESS_DT_TM]
			   ,[LAST_PROCESS_DT_TM]
			   ,[UPDT_DT_TM]
			   ,[UPDT_TASK]
			   ,[UPDT_USER]
			   ,[CDE_FILENAME]
			   ,[ROW_ID]
			   ,[TIMESTAMP_RECORD_ADDED]
			   ,[TIMESTAMP_RECORD_UPDATED])
	SELECT 
				row_number() over (partition by session_sk order by cast(UPDT_DT_TM as datetime) desc ) as Session_Sequence_NBR
			   ,[EDW_F_SESSION_ID]
			   ,[HEALTH_SYSTEM_SOURCE_ID]
			   ,[SESSION_SK]
			   ,[SESSION_BEG_DT_TM]
			   ,[LOC_SESSION_BEG_DT_TM]
			   ,[SESSION_END_DT_TM]
			   ,[LOC_SESSION_END_DT_TM]
			   ,[SESSION_DURATION]
			   ,[THEATRE_REF]
			   ,[NUMBER_OF_PLANNED_CASES]
			   ,[TOT_SCHED_CASE_TIME_MINS]
			   ,[NUMBER_OF_ACTUAL_CASES_HELD]
			   ,[OBSERVED_CASE_TIME_MINS]
			   ,[OBSERVED_ANESTHESIA_TIME_MINS]
			   ,[OBSERVED_SURGERY_TIME_MINS]
			   ,[TOTAL_COLLECTION_TIME_MINS]
			   ,[ACTUAL_FIRST_CASE_START_DT_TM]
			   ,[LOC_ACTUAL_FRST_CASE_STR_DT_TM]
			   ,[SCHED_FIRST_CASE_START_DT_TM]
			   ,[LOC_SCHED_FRST_CASE_STRT_DT_TM]
			   ,[NUMBER_OF_DELAYS]
			   ,[TOTAL_DELAY_DURATION_MINS]
			   ,[TOTAL_TURNAROUND_TIME_MINS]
			   ,[ACTUAL_LAST_CASE_STOP_DT_TM]
			   ,[LOC_ACTUAL_LAST_CASE_STP_DT_TM]
			   ,[NUMBER_OF_CANCELLATIONS]
			   ,[NUMBER_SAME_DAY_CANCELLATIONS]
			   ,[UNDER_UTILISATION_MINS]
			   ,[SCHED_LAST_CASE_STOP_DT_TM]
			   ,[LOC_SCHED_LAST_CASE_STOP_DT_TM]
			   ,[TOT_TIME_PAT_IN_THEATRE_MINS]
			   ,[EXTRACT_DT_TM]
			   ,[FIRST_PROCESS_DT_TM]
			   ,[LAST_PROCESS_DT_TM]
			   ,[UPDT_DT_TM]
			   ,[UPDT_TASK]
			   ,[UPDT_USER]
			   ,[CDE_FILENAME]
			   ,[ROW_ID]
			   ,[TIMESTAMP_RECORD_ADDED]
			   ,[TIMESTAMP_RECORD_UPDATED]    
	FROM [NON_CDE_EDW_F_Session]        

CREATE NONCLUSTERED INDEX [NON_CDE_EDW_F_Session_WITH_SEQUENCE_Index]
ON [dbo].[NON_CDE_EDW_F_Session_WITH_SEQUENCE] ([Session_Sequence_NBR])
INCLUDE ([SESSION_SK],[SESSION_BEG_DT_TM],[LOC_SESSION_BEG_DT_TM],[SESSION_END_DT_TM],[LOC_SESSION_END_DT_TM],[NUMBER_OF_PLANNED_CASES],[NUMBER_OF_ACTUAL_CASES_HELD],[ACTUAL_FIRST_CASE_START_DT_TM],[SCHED_LAST_CASE_STOP_DT_TM],[LOC_SCHED_LAST_CASE_STOP_DT_TM])

CREATE NONCLUSTERED INDEX [NON_CDE_EDW_F_Session_WITH_SEQUENCE_Session_Index]
ON [dbo].[NON_CDE_EDW_F_Session_WITH_SEQUENCE] ([Session_Sequence_NBR],[SESSION_SK])
INCLUDE ([SESSION_BEG_DT_TM],[LOC_SESSION_BEG_DT_TM],[SESSION_END_DT_TM],[LOC_SESSION_END_DT_TM],[NUMBER_OF_PLANNED_CASES],[NUMBER_OF_ACTUAL_CASES_HELD],[ACTUAL_FIRST_CASE_START_DT_TM],[SCHED_LAST_CASE_STOP_DT_TM],[LOC_SCHED_LAST_CASE_STOP_DT_TM])
	          
END

GO


